version: "3"

services:
  node:
    build:
      context: .
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: "syndication"
      MYSQL_HOST: "mariadb"
      NODE_ENV: "production"
      PORT: "3000"
    ports:
      - "3000:3000"
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "syndication"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_INITDB_SKIP_TZINFO: 1 # improves startup time
  mariadb_test:
    image: mariadb:10.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_INITDB_SKIP_TZINFO: 1 # improves startup time
    ports:
      - "3002:3306"
